name: Manually trigger for deploy to Firebase
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: frontend

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: frontend

      # - uses: bahmutov/npm-install@HEAD
      #   with:
      #     working-directory: frontend
        
      # - name: Build frontend dependencies
      #   run: yarn build
      #   working-directory: frontend
        
      - name: Copy frontend to public firabase structure
        run: cp -a frontend/dist/. public/

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAND_UP_QUOTES }}
          projectId: stand-up-quotes
          channelId: production
      
