name: Manually trigger for deploy to Firebase
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

#     DO WE REALLY NEED THIS?
#       - name: Install yarn
#         run: npm install -g yarn
#    /DO WE REALLY NEED THIS?

      - uses: actions/cache@v2
        id: firebase-bin
        with:
          path: ./firebase_bin
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}

      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: frontend
      
      - name: Download firebase binary if not in cache or os change
        if: steps.firebase-bin.outputs.cache-hit != 'true'
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
        
      - name: Build frontend dependencies
        run: yarn build
        working-directory: frontend
        
      - name: Copy frontend to public firabase structure
        run: cp -a frontend/dist/. public/
      
      - name: Deploy to Firebase
        run: |
          chmod 755 ./firebase_bin
          ./firebase_bin deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}

      
      
