name: Manually trigger for deploy to Firebase
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install frontend dependencies
        run: cd frontend-vue && yarn build
      - name: Copy frontend to public firabase structure
        run: cp -a frontend-vue/dist/. public/
      - name: Deploy to Firebase
        run: |
          sudo yarn add firebase
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}

      
      
